const plantsData = [
    { id: 0, name: "Rose", category: "Ornamental", price: 150, description: "A beautiful ornamental flower available in multiple colors.", imageUrl: "/images/rose.jpg" },
    { id: 1, name: "Tulsi", category: "Medicinal", price: 100, description: "A sacred plant known for its medicinal properties.", imageUrl: "/images/tulsi.jpg" },
    { id: 2, name: "Money Plant", category: "Indoor", price: 200, description: "A popular indoor plant that symbolizes good luck.", imageUrl: "/images/money-plant.jpg" },
    { id: 3, name: "Snake Plant", category: "Indoor", price: 250, description: "Low maintenance and excellent air purifier.", imageUrl: "/images/snake-plant.jpg" },
    { id: 4, name: "Aloe Vera", category: "Medicinal", price: 120, description: "A versatile plant known for its healing properties.", imageUrl: "/images/aloe-vera.jpg" },
    { id: 5, name: "Jasmine", category: "Ornamental", price: 180, description: "Fragrant flowers that thrive in sunny conditions.", imageUrl: "/images/jasmine.jpg" },
    { id: 6, name: "Fern", category: "Indoor", price: 160, description: "A lush green plant perfect for shady spots.", imageUrl: "/images/fern.jpg" },
    { id: 7, name: "Neem", category: "Medicinal", price: 130, description: "A traditional Indian tree with numerous health benefits.", imageUrl: "/images/neem.jpg" },
    { id: 8, name: "Bamboo", category: "Indoor", price: 300, description: "Symbol of strength and prosperity, great indoors.", imageUrl: "/images/bamboo.jpg" },
    { id: 9, name: "Orchid", category: "Ornamental", price: 500, description: "Elegant flowering plant with exotic blooms.", imageUrl: "/images/orchid.jpg" },
    { id: 10, name: "Hibiscus", category: "Ornamental", price: 170, description: "Bright and cheerful flowers that bloom year-round.", imageUrl: "/images/hibiscus.jpg" },
    { id: 11, name: "Basil", category: "Herbal", price: 90, description: "A culinary herb with aromatic leaves.", imageUrl: "/images/basil.jpg" },
    { id: 12, name: "Spider Plant", category: "Indoor", price: 140, description: "Hardy indoor plant with air-purifying qualities.", imageUrl: "/images/spider-plant.jpg" },
    { id: 13, name: "Pickle Cactus", category: "Succulent", price: 200, description: "Low maintenance plant perfect for dry environments.", imageUrl: "/images/pickle-cactus.jpg" },
    { id: 14, name: "Lavender", category: "Herbal", price: 250, description: "Aromatic plant known for its calming fragrance.", imageUrl: "/images/lavender.jpg" },
    { id: 15, name: "Peperomia", category: "Indoor", price: 190, description: "Compact plant with vibrant foliage.", imageUrl: "/images/peperomia.jpg" },
    { id: 16, name: "Begonia", category: "Ornamental", price: 210, description: "Colorful flowering plant ideal for shaded areas.", imageUrl: "/images/begonia.jpg" },
    { id: 17, name: "Chrysanthemum", category: "Ornamental", price: 240, description: "Symbol of happiness, available in many colors.", imageUrl: "/images/chrysanthemum.jpg" },
    { id: 18, name: "Ficus", category: "Indoor", price: 300, description: "Elegant foliage plant for indoor spaces.", imageUrl: "/images/ficus.jpg" },
    { id: 19, name: "Palm", category: "Indoor", price: 450, description: "Tall and lush, perfect for modern interiors.", imageUrl: "/images/palm.jpg" },
    { id: 20, name: "Lily", category: "Ornamental", price: 280, description: "Elegant flowering plant for indoor or outdoor spaces.", imageUrl: "/images/lily.jpg" },
    { id: 21, name: "Mint", category: "Herbal", price: 80, description: "Fresh and aromatic herb for culinary use.", imageUrl: "/images/mint.jpg" },
    { id: 22, name: "Philodendron", category: "Indoor", price: 260, description: "Popular indoor plant with lush foliage.", imageUrl: "/images/philodendron.jpg" },
    { id: 23, name: "Croton", category: "Ornamental", price: 270, description: "Brightly colored foliage for indoor and outdoor use.", imageUrl: "/images/croton.jpg" },
    { id: 24, name: "Marigold", category: "Ornamental", price: 90, description: "Cheerful and easy-to-grow flowering plant.", imageUrl: "/images/marigold.jpg" },
    { id: 25, name: "Geranium", category: "Ornamental", price: 230, description: "Vibrant blooms that thrive in pots and gardens.", imageUrl: "/images/geranium.jpg" },
    { id: 26, name: "Rubber Plant", category: "Indoor", price: 350, description: "Striking indoor plant with glossy leaves.", imageUrl: "/images/rubber-plant.jpg" },
    { id: 27, name: "Bougainvillea", category: "Outdoor", price: 400, description: "Hardy flowering plant with vibrant blooms.", imageUrl: "/images/bougainvillea.jpg" },
    { id: 28, name: "Pothos", category: "Indoor", price: 120, description: "Low maintenance trailing plant.", imageUrl: "/images/pothos.jpg" },
  ];
  
  export default plantsData;
  